[FIX] mollie_pos_terminal: js error when clicking on 'back' during payment
Instead of opening the popup 'Cancel mollie payment' an error is thrown,
break the UI.

js error:
TypeError: line.payment_method.payment_terminal.send_payment_cancel(...).finally is not a function